Feature/add union data
fivetran/dbt_hubspot_source pull request #123
Opened 2024-01-08 15:57 UTC by fivetran-jamie

## PR Overview
**This PR will address the following Issue/Feature:**
https://github.com/fivetran/dbt_hubspot/issues/130

**This PR will result in the following new package version:**

v0.15.0

**Please detail what change(s) this PR introduces and any additional information that should be known during the review of this PR:**
introduces support for running the package on a union of connectors
- adds `union_data` macro to each _tmp model 
- includes source relation in each staging model
- adds yml documentation for source_relation
- includes source_relation in all uniqueness tests 
- documents unioning ability in README

## PR Checklist
### Basic Validation
Please acknowledge that you have successfully performed the following commands locally:
- [ ] dbt compile
- [ ] dbt run –full-refresh
- [ ] dbt run
- [ ] dbt test
- [ ] dbt run –vars (if applicable)

Before marking this PR as "ready for review" the following have been applied:
- [ ] The appropriate issue has been linked and tagged
- [ ] You are assigned to the corresponding issue and this PR
- [ ] BuildKite integration tests are passing

### Detailed Validation
Please acknowledge that the following validation checks have been performed prior to marking this PR as "ready for review":
- [ ] You have validated these changes and assure this PR will address the respective Issue/Feature.
- [ ] You are reasonably confident these changes will not impact any other components of this package or any dependent packages.
- [ ] You have provided details below around the validation steps performed to gain confidence in these changes.

### Standard Updates
Please acknowledge that your PR contains the following standard updates:
- Package versioning has been appropriately indexed in the following locations:
    - [x] indexed within dbt_project.yml
    - [ ] indexed within integration_tests/dbt_project.yml
- [ ] CHANGELOG has individual entries for each respective change in this PR
    
- [x] README updates have been applied (if applicable)
    
- [ ] DECISIONLOG updates have been updated (if applicable)
- [x] Appropriate yml documentation has been added (if applicable)

### dbt Docs
Please acknowledge that after the above were all completed the below were applied to your branch:
- [ ] docs were regenerated (unless this PR does not include any code or yml updates)

### If you had to summarize this PR in an emoji, which would it be?
 
🇨🇱

2024-01-09 14:30 UTC, fivetran-jamie commented on README.md
> +> **Note**: If you are running the package on one source connector, each model will have a `source_relation` column that is just an empty string.
this is probably gonna change pending catherine's updates

2024-02-02 21:50 UTC, fivetran-joemarkiewicz requested changes
@fivetran-jamie the results of this PR look great! I just have a few questions and suggestions in the comments below that I would like your eyes on before we approve this. Let me know if you have any questions or want to chat about these further.

2024-02-02 21:50 UTC, fivetran-joemarkiewicz commented on models/stg_hubspot__company.sql
> +                prefix='property_', exclude=(get_macro_columns(get_company_columns()) + ['_dbt_source_relation']))
Can you explain the need for this addition?

2024-02-02 21:50 UTC, fivetran-joemarkiewicz commented on models/stg_hubspot__company.sql
> +                prefix='property_', exclude=(get_macro_columns(get_company_columns()) + ['_dbt_source_relation']))
This comment applies to the other models with the similar code update.

2024-02-02 21:50 UTC, fivetran-joemarkiewicz commented on packages.yml
> +
Reminder to swap before release

2024-02-05 16:18 UTC, fivetran-jamie commented on CHANGELOG.md
> +# dbt_hubspot_source v0.15.0
hm that is a good question..i'd be curious to hear what the team thinks, as i think we've only used v1.0.0 for [ad reporting](https://github.com/fivetran/dbt_ad_reporting/releases/tag/v1.0.0) and when we renamed fivetran log to fivetran platform. 

what sorts of updates merit a major version change?

2024-02-05 18:37 UTC, fivetran-jamie commented on CHANGELOG.md
> +- Included Github Actions workflow to check for docs updates.
removed

2024-02-05 23:56 UTC, fivetran-jamie commented on README.md
> +  <details><summary><i>Expand for source configuration template</i></summary><p>
updated

2026-01-20 19:58 UTC, closed without merging