Update/crm api v3 - contact merge audit removed
fivetran/dbt_hubspot_source pull request #98
Opened 2023-03-21 23:03 UTC by fivetran-jamie

**Are you a current Fivetran customer?** 

internal 

**What change(s) does this PR introduce?** 

aligns with recent [changes](https://fivetran.com/docs/applications/hubspot/changelog#november2022) to the hubspot API 
- adds the new `property_hs_calculated_merged_vids` field to the contact table seed data
- explicitly casts all timestamp fields as timestamps
- adds BigQuery-specific logic since the above connector change is blocked on BQ. Thus, they will have to use the old behavior, but we want to make it so that they can switch to the new way if they want (by setting `hubspot_contact_merge_audit_enabled` to FALSE.

**Did you update the CHANGELOG?** 

- [ ] Yes

**Does this PR introduce a breaking change?**

- [x] Yes (please provide breaking change details below.)
- [ ] No  (please provide an explanation as to how the change is non-breaking below.)

the default behavior will change! except for BQ people

**Did you update the dbt_project.yml files with the version upgrade (please leverage standard semantic versioning)? (In both your main project and integration_tests)** 

- [x] Yes

**Is this PR in response to a previously created Bug or Feature Request**

- [x] Yes, Issue/Feature https://github.com/fivetran/dbt_hubspot_source/issues/97 + https://github.com/fivetran/dbt_hubspot/issues/97
- [ ] No 

**How did you test the PR changes?** 

 

- [x] Buildkite  
- [x] Local (please provide additional testing details below)

**Select which warehouse(s) were used to test the PR**
 

- [x] BigQuery
- [x] Redshift
- [x] Snowflake
- [x] Postgres
- [x] Databricks
- [ ] Other (provide details below)

**Provide an emoji that best describes your current mood**
 
😩 

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

2023-03-22 00:57 UTC, fivetran-jamie commented
will regen docs before merging

2023-03-23 20:32 UTC, fivetran-joemarkiewicz requested changes
@fivetran-jamie just a few minor requests and callouts. Let me know if you have any other questions!

2023-03-24 20:22 UTC, fivetran-jamie commented on CHANGELOG.md
> +  - In [November 2022](https://fivetran.com/docs/applications/hubspot/changelog#november2022), the Fivetran Hubspot connector switched to v3 of the Hubspot CRM API, which deprecated the `CONTACT_MERG
bumped drew but he's ooo till monday

2023-03-24 20:23 UTC, fivetran-jamie commented on models/src_hubspot.yml
> +          enabled: "{{ var('hubspot_marketing_enabled', true) and var('hubspot_contact_merge_audit_enabled', target.type == 'bigquery') }}"
just gotta return a boolean!

2023-03-24 20:23 UTC, fivetran-jamie commented on CHANGELOG.md
> +# dbt_hubspot_source v0.9.0 or v0.8.1 - breaking or na
updating

2023-03-24 20:24 UTC, fivetran-jamie commented on CHANGELOG.md
> +  - Updates seed data to test new merging paradigm.
cool also gonna move the `Ensures that all timestamp fields are explicitly cast as timestamps without timezone` part there as well

2023-03-28 16:58 UTC, fivetran-joemarkiewicz requested changes
@fivetran-jamie this is looking great and I feel it is very close to being able to merge through. I do just have one remaining comment regarding the `hubspot_contact_merge_audit_enabled` variable and how we use it for BigQuery users. I think we need to rethink how we use this variable. We can chat during standup.

Additionally, I came across a bug when doing more rigorous testing and ended up opening PR #100 to address the issue. We can batch this with these changes. It would be great if you could review.

2023-03-28 16:58 UTC, fivetran-joemarkiewicz commented on models/src_hubspot.yml
> +          enabled: "{{ var('hubspot_marketing_enabled', true) and var('hubspot_contact_merge_audit_enabled', target.type == 'bigquery') }}"
@fivetran-jamie after what we adjusted in the transform package, should we use this approach here? Not all bigquery customers will want to have `hubspot_contact_merge_audit_enabled` set as `true` by default.

2023-03-28 17:36 UTC, fivetran-jamie commented on models/src_hubspot.yml
> +          enabled: "{{ var('hubspot_marketing_enabled', true) and var('hubspot_contact_merge_audit_enabled', target.type == 'bigquery') }}"
updated

2023-03-28 20:08 UTC, fivetran-joemarkiewicz approved these changes
Thanks for working through the updates @fivetran-jamie! After final review, these look good to go!

2023-03-28 20:15 UTC, merged